### ISSUE TITLE
人物発見について

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT/TC2016_for_thirdrobot#1]
今回はちゃんと人物発見タスクに取り組みたいと思います。

まず、３DLidarを搭載し、よく使われているという反射強度についてテストを行いました。
今回はLidarから得られる点群を２フレーム分利用しています。つまり、センサの周波数は10Hzになります。ロボットを移動させた感じではつくばチャレンジでのロボットの移動速度では問題にならないと思います。
以下がそのスクリーンショットになります。
着用しているベストと看板は本番で使われているものと同様のものです。看板には反射テープのみを貼り付けています。
確かに、反射強度が他に比べて強くなっていることが確認できます。
またこの時のLidarから看板までの距離は2.1[m]でした。
ここからどのような手法を使うことが考えられるかなどありましたら教えていただければ幸いです。

![screenshot from 2016-10-06 19 55 24](https://cloud.githubusercontent.com/assets/8924428/19150718/5db97e16-8c03-11e6-8a32-1867a7d3fa36.png)
![bf3b82cb-db82-4151-aff7-8f20e662fbd9](https://cloud.githubusercontent.com/assets/8924428/19150731/6ef1fb04-8c03-11e6-8037-d43dd1e97e15.JPG)

**Comment by AriYu** [comment]
まずはSVMを使って識別器を作ってみようと思います。

**Comment by MoriKen254** [comment]
@AriYu 
よろしければ，SVMを使った人物検出器を作るときに参考にしている文献があれば共有してもらえますか？
私も知っておきたいです．

**Comment by AriYu** [comment]
@MoriKen254 
特徴量に関しては研究室で人物発見に使われているものをまずは試してみようと思っています。今はそのまま利用しているだけですので、細かい仕様とかはわかりません。ただ、点群の分散や固有値を使っているみたいです。
また、実装はlibsvmを使おうかと思っています。

**Comment by AriYu** [comment]
@MoriKen254 
特徴量に関して参考にした文献を示します。
[1] Liu, Kun, and Jan Boehm. "Classification of Big Point Cloud Data Using Cloud Computing." The International Archives of Photogrammetry, Remote Sensing and Spatial Information Sciences 40.3 (2015): 553.
[2] 城殿清澄, et al. "高解像度レーザレーダによる歩行者識別." 日本ロボット学会誌 29.10 (2011): 963-970.
文献[1]のTable1の特徴量と文献[2]の式(4)の特徴量を組み合わせているとのことです。

**Comment by AriYu** [comment]
現状での進捗ですが、ある程度対象に近づくとちゃんと認識できるようににはなっています。ただ、学習データに２００程度しか使っていないのでまだまだ向上する可能性はあります。
誤検出もありますが、false-positiveな間違いなので大丈夫だと思います。間違って認識しても減点はありません。
![screenshot from 2016-10-10 14 59 50](https://cloud.githubusercontent.com/assets/8924428/19227875/35d492c4-8efa-11e6-9cfd-973514ffdf9b.png)
上の結果は正しく認識できています。

ただ、これから何をすればいいのかがイマイチ分からなくて、追跡をすべきか、毎フレームごとに検出をするのか、前に検出したものと同一である判定であったりと、知恵を貸して頂けると幸いです。

あと、点群を処理しているから分かりませんが、少し重たいです。最悪コアを一つ使いきってしまいそうな感じで重たいです。

**Comment by MoriKen254** [comment]
@AriYu 
参考文献ありがとうございます．是非参考にさせていただきます．

早速人物検出ができたということで，すばらしいです．
何をすべきかの件も，了解です．何かたたき台があった方が良さそうですね．

来週木曜日の歓迎会に行けそうなので，それまでに各自案を出しましょうか．可能なら事前にここに共有しておくと言うことで． マシンに依存しない課題なので，@RyodoTanaka くんも是非 ^^

点群が重いのは，人物検出のときだけですか？通常の運転中でも重いとなると，悩ましいですが...．

**Comment by MoriKen254** [comment]
人物検出のルールで気になる記述があります。下記ページの一番最後。

http://www.tsukubachallenge.jp/tc2016/kadai#searcharea

> （注2）ただし、つくばチャレンジ2016では、探索対象以外の人（やもの）を見つけて、そこに停止した回数は、誤認識として記録に残すこととします。

false-positiveは減点対象になる、と言うことかと思います。念のため、確認です。

**Comment by MoriKen254** [comment]
@AriYu @RyodoTanaka 
突貫の案です。概念図と状態遷移図を上げます。議論のたたき台になれば幸いです。

![_](https://cloud.githubusercontent.com/assets/12078261/19255627/e02aaa6a-8f9a-11e6-8666-d09e76411606.png)

![_](https://cloud.githubusercontent.com/assets/12078261/19255629/e44e88aa-8f9a-11e6-9979-6de2768bba49.png)

**Comment by AriYu** [comment]
@MoriKen254 
まず、誤認識の件ですが、確かに誤認識の回数を記録するようですが、課題達成には関係ないということで、あまりこだわらないようにしたいと思います。
確認ありがとうございました。

状態遷移の提案ありがとうございます。
確かにwaypointに自体に人物探索に関するフラグを持っておくのはいいですね。
このアイディアで少し実装してみます。

**Comment by AriYu** [comment]
進捗ですが、地図に発見した探索対象の場所を表示するところまでは出来ました。
しかし、予想以上に誤検出が多いことが問題です。
まだsvmのモデルの訓練データが少なく、もっと精度が向上することは考えられますが、追加で何か簡単な識別器もしくは条件が付け加えられればいいかなと思っています。
以下の動画は今回の実験の様子です。探索対象とランダムに歩きまわっている人がいる状況です。
最後まで残っているボックスが探索対象と認識したものになります。
https://youtu.be/_AiFR_FApjs

**Comment by MoriKen254** [comment]
進捗、素晴らしいですね。ここまで動いていればあと一歩ですね。

追加の識別器としては、反射強度、ジャケット色、看板認識と言う所でしょうか。

完成が楽しみです！

**Comment by MoriKen254** [comment]
Gazeboでも本番でも人物と角の区別ができませんでした。改善の道筋は立てておきたいところです。

学習データを増やすことで解決できるのか、何かしきい値等で改善できるのか、識者に確認しましょう。

**Comment by AriYu** [comment]
続きは`human_detector`でやりましょう。
