### ISSUE TITLE
現地実験走行までのTODO

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/TC2016_for_thirdrobot#11]
実機発送後から現地実験走行まで間に、できるだけ不具合を減らすにはgazeboでの検証環境が大切と思います。
以下、gazeboでシステム検証、デバッグするためのTODOリストです。
## 最優先 (10/31中にできたら最高．遅くとも11/1．)
- [x] detector での人物検出時の負荷を低減させる(ループのデバッグ)。@AriYu 
- [x] navigator, fakeの使い方をドキュメント化。@AriYu 
- [x] gazeboでナビゲーション再現。@MoriKen254 
- [x] navigator, fakeをgazeboで動かしてシステム検証、デバッグ。@AriYu @MoriKen254 

## 優先 (11/1までにできたら最高．遅くとも11/2．)
- [x] detectorをgazeboで検証できるように看板＋人のurdfモデルを作成。 @MoriKen254
- [ ] ~~看板＋人のurdfモデルで機械学習。~~ 
- [x] detector込みのナビゲーションをgazeboで動かしてシステム検証、デバッグを。 @AriYu @MoriKen254 

## 最悪やらなくてもいいけど簡単なのですぐやるべき
- [x] recovery 実施時に何かtopicを投げる。@MoriKen254 
- [ ] navigator がrecoveryからtopicを受け取った際、abort判定までの時間を短縮させる。@AriYu
- [x] monitor の表示をかっこよくする。@MoriKen254 

ただ、身体を壊してまで全てやる必要はありません。
本番に備えて休息を取るのも仕事なので、様子を見ながらやりましょう。

本当にあと一歩です。何とか頑張りましょう！

**Comment by AriYu** [comment]
@MoriKen254 
まず、
> detector での人物検出時の負荷を低減させる(ループのデバッグ)。
に関してですが、高負荷時のCPU使用率を調べた結果、`move_base`がハングしていることが分かりました。
その後、いろいろな実験の後、goal座標を障害物の上に置いた場合、プランが計算できなくなるという問題であるということが分かりました。これは`fake_detector`では再現出来てなかったことで、当然といえば当然のことです。
とりあえず、`default_tolerance`というパラメータを`1.0`にすることでその問題を回避できることを確かめました。しかし、goal座標が探索対象の裏側に行ってしまったりとあまり綺麗なパスが生成されません。また復帰に時間が掛かってしまいます。
http://wiki.ros.org/navfn

そこで、探索対象を見つけた時の目標座標をちゃんと計算することに挑戦してみます。
簡単ではありますが、ロボットの現在位置と探索対象の位置を結んだ直線と探索対象を中心とした円の交点を求めロボットに近い交点を目標座標としてみます。

**Comment by AriYu** [comment]
また、障害物があるにも関わらずロボットが進んでしまう問題がありましたが、その問題が起きる場合にはリカバリが発動したわけでも無いにも関わらずローカルコストマップが完全にクリアされていました。
この問題に関しては検討がついておりません。

**Comment by MoriKen254** [comment]
@AriYu 
連絡ありがとうございます。

detctorの件、分かりました。

後者は、条件は分かりませんよね…。cpu負荷が高い探索中に起きたとかなら分かりそうですが。

あるいは、リカバリ行動前に発動するclearcostmapとの関連はあるかもしれません。
リカバリを反映させるときにプランナーのyamlを設定したと思いますが、その中にclearcostmapの設定も入れてあるはずです。ただ、これを外すと今度は定常状態で経路が見つかりにくくなるかと。

今はそれくらいしか思い浮かびませんf^_^; 取り急ぎ。

**Comment by AriYu** [comment]
探索対象を見つけた場合にはアプローチすることができるようになりました。
ただ、アプローチに時間が掛かってしまうため、このままだとゴールする前に制限時間を超えてしまう可能性があります。
制限時間を考慮するようにするか、もう少し綺麗なアプローチをする必要があるかもしれません。
あと誤検出が多すぎです。

**Comment by AriYu** [comment]
navigatorなどの使い方を追記しました。
何かわかりにくい記述やわからないことがあれば教えてください。
よろしくお願いします。

**Comment by MoriKen254** [comment]
@AriYu 
ありがとうございます．レス遅れてすみません．
急ぎ当方で検証してみます．

**Comment by MoriKen254** [comment]
@AriYu 
ナビゲーションでてこずっています^^;

TC2016_for_thirdrobot，third_robot_pkgいずれも，ブランチは`add_gazebo_navigation_setting`です．
とりあえずwaypointは作れたようです．

以下，実施した作業と現象を書きます．

### waypoint generater
作成済みです．

2016-11-01-04-01-48.csv

### Gazebo起動
```bash
roslaunch third_robot_2dnav_gazebo autorun.launch
```

### Gazebo位置合わせ
移動のしやすさを考慮して初期値を変更する．
Gazebo上でロボットの位置をずらし，rviz上で2d pose estimate も修正．（自動化したいがうまくいかない）

![screenshot from 2016-11-01 04 26 30](https://cloud.githubusercontent.com/assets/12078261/19868852/3b5903ca-9fed-11e6-9c8f-dadb61838ca8.png)

![screenshot from 2016-11-01 04 26 21](https://cloud.githubusercontent.com/assets/12078261/19868857/42658a9e-9fed-11e6-9be9-38c4ee4bcb9d.png)


### waypoint ロード
```bash
roscd waypoint_navigator/waypoints/
rosrun ros_waypoint_generator ros_waypoint_generator --load 2016-11-01-04-01-48.csv 
```

表示は正しいよう．フィールドをぐるっと一周させている．

![screenshot from 2016-11-01 04 27 00](https://cloud.githubusercontent.com/assets/12078261/19868886/5942026a-9fed-11e6-9ef1-cd64af14ecd9.png)

### navigater 起動

``` bash
roslaunch waypoint_navigator waypoint_navigator_gazebo.launch
```

下記のように表示され，すぐにエラーまでいく．

```bash
[ INFO] [1477942103.163601855]: [Waypoints file name] : /home/morita/Documents/dev/ros/tc2016_ws/src/TC2016_for_thirdrobot/waypoint_navigator/waypoints/tobata2016-with-search-area-2m.csv
[ INFO] [1477942103.168589306]: Reading Waypoints.
[ INFO] [1477942103.178937983]: Waiting for action server to start.
[ INFO] [1477942103.400504056, 1500.410000000]: Next Waypoint : 0
[ INFO] [1477942103.400553536, 1500.410000000]: Next WayPoint is got
[ INFO] [1477942103.400574494, 1500.410000000]: Go next_waypoint.
[ERROR] [1477942103.400889202, 1500.410000000]: Lookup would require extrapolation into the past.  Requested time 1500.410000000 but the earliest data is at time 1500.420000000, when looking up transform from frame [base_link] to frame [map]
[ERROR] [1477942103.401017261, 1500.410000000]: Lookup would require extrapolation into the past.  Requested time 1500.410000000 but the earliest data is at time 1500.420000000, when looking up transform from frame [base_link] to frame [map]
```

その後wayポイントが無関係なところに設定される．フィールドの中心に向かう．

![screenshot from 2016-11-01 04 29 32](https://cloud.githubusercontent.com/assets/12078261/19868949/97b1c896-9fed-11e6-87fe-f40d8b10fe48.png)

移動の途中で下記のメッセージが表示される．

```bash
[ INFO] [1477942133.496732639, 1530.510000000]: Waiting Abort: passed 30s, Distance to goal: 13.0778
[ INFO] [1477942163.609342729, 1560.610000000]: Waiting Abort: passed 30s, Distance to goal: 6.60787
[ INFO] [1477942193.531312332, 1590.510000000]: !! WAYPOINT_NAV_PLANNING_ABORTED !!
[ INFO] [1477942193.531358164, 1590.510000000]: cancelGoal() is called !!
[ INFO] [1477942193.631136539, 1590.610000000]: Next Waypoint : 0
[ INFO] [1477942193.631202141, 1590.610000000]: Next WayPoint is got
[ INFO] [1477942193.631235285, 1590.610000000]: Go next_waypoint.
[ INFO] [1477942194.031931419, 1591.010000000]: Distance: 1.49941
[ INFO] [1477942194.032004960, 1591.010000000]: WAYPOINT_REACHED_GOAL
[ INFO] [1477942194.131841070, 1591.110000000]: Next Waypoint : 1
[ INFO] [1477942194.131919906, 1591.110000000]: Next WayPoint is got
[ INFO] [1477942194.131947473, 1591.110000000]: Go next_waypoint.
[ INFO] [1477942195.932623554, 1592.910000000]: Distance: 1.48942
[ INFO] [1477942195.932743829, 1592.910000000]: WAYPOINT_REACHED_GOAL
[ INFO] [1477942196.032331658, 1593.010000000]: Next Waypoint : 2
[ INFO] [1477942196.032366643, 1593.010000000]: Next WayPoint is got
[ INFO] [1477942196.032378558, 1593.010000000]: Go next_waypoint.
```

中央辺りで，当初登録していないwaypointが追加された模様．
なお，移動中は一度も停止しておらず，最終的には壁まで衝突する．

**Comment by AriYu** [comment]
@MoriKen254 
異なるwaypointファイルが読み込まれているようですね。
`waypoint_navigator/launch/waypoint_navigator.launch`の中の`waypointsfile`パラメータを確認していただけますか？

**Comment by AriYu** [comment]
> `rosrun ros_waypoint_generator ros_waypoint_generator --load 2016-11-01-04-01-48.csv `

の`--load`オプションは再度そのwaypointを利用して編集したり確認するオプションですので、これを実行していても特にnavigationには関係ありません。
わかりにくくて申し訳ありません。

**Comment by MoriKen254** [comment]
@AriYu 

> 異なるwaypointファイルが読み込まれているようですね。
すみません，その通りでした．変えたつもりだったのですが…．

> --loadオプションは再度そのwaypointを利用して編集したり確認するオプション
ナビに関係ないのは認識していたのですが，`waypoint_navigator/launch/waypoint_navigator.launch`からインタラクティブマーカ型のトピックが見つけられず，可視化のために起動していました．

実験したときのように，ナビゲーション中のwaypointをrvizで監視するにはどうすればよいでしょうか？

**Comment by AriYu** [comment]
@MoriKen254 
実験していた時は同様に`--load`オプションを使っていました。移動する度にwaypointが追加されてしまいますが、走行には問題にならないのでそうしていました。
しかし走行中にも確認したいので追加で`waypoint_server`プログラムを書きたいと思います。

**Comment by AriYu** [comment]
@MoriKen254 
waypointを確認するたのノードを追加しました。`ros_waypoint_generator`の更新をお願いします。
```
rosrun ros_waypoint_generator ros_waypoint_server --load path/to/waypoints.csv
```
![screenshot from 2016-11-01 19 52 43](https://cloud.githubusercontent.com/assets/8924428/19887759/a960df16-a06d-11e6-8586-6f7cf5cc8b54.png)

**Comment by MoriKen254** [comment]
@AriYu 
素晴らしい！ありがとうございます．

なお，どちらのブランチで取得できますか？

**Comment by AriYu** [comment]
@MoriKen254 
すでにマージしてあるので、masterブランチで :ok: です

**Comment by MoriKen254** [comment]
@AriYu 
ばっちりです．ありがとう．

遠隔監視側も改造しました．

https://github.com/CIR-KIT/third_robot_pkg/pull/42

![monitor](https://cloud.githubusercontent.com/assets/12078261/19892735/c6821a4e-a089-11e6-8a35-2438465eef27.png)

**Comment by AriYu** [comment]
@MoriKen254 
すごくいい感じです。要望を聞いていただきありがとうございます。
マージしました。

**Comment by AriYu** [comment]
本番は無事終わったので閉じます。
