### ISSUE TITLE
つくばチャレンジ2016現地の地図

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT/TC2016_for_thirdrobot#24]
つくばチャレンジ2016の全地図です。
ご査収ください。頑張ります。
@MoriKen254 
https://drive.google.com/drive/folders/0B1BG29bV6tIuQkdOLXBxLVJUWDQ?usp=sharing

**Comment by MoriKen254** [comment]
完走おめでとう^^

今日のモニタ結果です．記念にどうぞ．

![screenshot from 2016-11-06 14 10 33](https://cloud.githubusercontent.com/assets/12078261/20037785/99f9f21e-a46a-11e6-9e36-f0511ae9751e.png)
