### ISSUE TITLE
つくばチャレンジ2016の参加レポート原稿依頼

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT/TC2016_for_thirdrobot#26]
つくばチャレンジ2016での成果を他チームと共有し、全体の技術レベルを高めるとを目的としたつくばチャレンジ参加レポート集の作成依頼をいただきました。

〆切は12/14です。
担当された箇所で共有できるという技術がありましたら、適当にTeXファイルで原稿を書いていただけますか。

チームは2つでしたので、2つ提出できますが、5号機を担当した皆さんはどうでしょうか。
とりあえず、書いてみてください。
詳細はメールが来ていると思いますので、それを参照してください。

**Comment by yasu80** [comment]
お知らせいただきありがとうございます. 承知しました. 

>詳細はメールが来ていると思いますので、それを参照してください。

出先から帰り次第(1~2日中), CIR-KIT のアカウントを確認します. 

記事内容については,
 ・ i-cart mini の特性について
 ・ T-frog TF-2MD3-R6 による Odometry 取得について
 ・ その他つくばチャレンジ現場での事象
などを考えています.

これも, 出先から帰り次第, 過去のレポートを調べるなどして, 詳細を決め, 草稿を作ろうと思っています.

**Comment by yasu80** [comment]
@AriYu 
すみません, 応答が遅れました...
先方に出す情報としてはこのような形で良いでしょうか.

チームナンバー：1653
チーム名:  CIR-KIT B
技術資料集原稿のタイトル：i-cart mini に よる ROS navigation の運用
著者のお名前：徳安 一
予定ページ数：5P

**Comment by AriYu** [comment]
提出したので閉じます。
御協力ありがとうございました。
