### ISSUE TITLE
探索対象にアプローチ後、次のwaypointが遠くになる

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT/TC2016_for_thirdrobot#9]
Pull #8 で人物発見時の動作を確認しましたが概ね上手く行っているように見えます。
もちろん、実際に探索器を走らせているわけではないので、認識することができれば上手く行きそうということです。
ただ、１回だけ、探索対象にアプローチ後waypointが数個飛ばされて更新されることがありました。

**Comment by MoriKen254** [comment]
@AriYu 
すばらしいですね！お疲れ様です^^

数個飛ばされて更新される件について，コードを眺めてみてのコメントです．動かしてみたわけではないので予想でしかありませんので悪しからず… ^^;

- waypoint_navigator.cpp: 306行目~316行目

```cpp
          for (int i = 0; i < target_objects_.boxes.size(); ++i) {
              // 省略
              if (distance_to_target < 15.0) {
                ROS_INFO_STREAM("Found new target objects.");
                this->setNextGoal(target_objects_.boxes[i], dist_thres_to_target_object_); // 探索対象を次のゴールに設定
                robot_behavior_state_ = RobotBehaviors::DETECT_TARGET_NAV;
                break;
              }else // 探索対象が見つかったが遠すぎる
              {
                ROS_INFO_STREAM("Found new target object, but too far.");
                this->setNextGoal(next_waypoint);
                robot_behavior_state_ = RobotBehaviors::WAYPOINT_NAV;
              }
              // 省略
          }
```

全ての`target_objects_.boxes`についてfor文を回している上記箇所で，思考実験をします．

もし「遠すぎる探索対象」がたまたま3個見つかっていたら，この配列にも3個分その情報が入ると考えます．かつ，15m以内の探索対象もこの配列には格納されておらず，310行目の`break`の分岐にも入らない場合を想定します．

すると，このforループは配列スキャン終了まで1度も`break`しません．つまり，forループを回し終わるまでの間に3回`this->setNextGoal(next_waypoint);`が呼ばれることになります．

結果として3回waypointが飛ばされることにはなる，という現象に繋がるとは考えられませんか？

お疲れと思いますので，お手すきの時に確認をお願いします^^
楽しみにしていたアメリカ行きと思いますので，ご自愛下さい．

**Comment by AriYu** [comment]
@MoriKen254 
コードまで読んでいただきありがとうございます。
確かに、その問題が起こったのは最後の探索対象を見つけたあとでした。そのへんがおかしいようですね。
助かりました。
解決は帰国後になりそうです。
パソコンは持っていかないと思うのでマージ等は各自で行ってもらって大丈夫です。
以上、よろしくお願いします。

**Comment by MoriKen254** [comment]
@AriYu 
諸々了解です。何か気になったらこちらでマスターブランチにマージしておきます。

すみません、これだけ最後に。帰国後休息をとった後でよいので、もし本番までに大学で実験の予定があれば、教えてもらえますか？私も御一緒させて下さい。もし可能であれば事前に伝えてもらえると調整がつけやすいので助かります。

しばらくはつくちゃを頭から少し離して、アメリカで思い切り楽しんで下さい！(^^)

**Comment by AriYu** [comment]
@Moriken254
返事が遅くなってしまって申し訳ありません。
30日に最後の実験をしたいと思います。
もしお時間があればよろしくお願いします。

**Comment by MoriKen254** [comment]
@AriYu 
返信ありがとう。是非御一緒させて頂きます。よろしくお願いします。

**Comment by AriYu** [comment]
Pull #10 で解決されたのでcloseします。
